# Generated by Django 5.1 on 2024-12-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='resume',
            field=models.FileField(default='No resume uploaded', upload_to='resumes/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='video',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
